# Generated by Django 4.0.2 on 2022-02-28 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('py_institute', '0004_ip_contact_date_myusers_last_logged_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeviceinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
