# Generated by Django 4.0.2 on 2022-03-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_institute', '0005_alter_userdeviceinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSAver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
