# Generated by Django 4.0.2 on 2022-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_institute', '0006_passwordsaver'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordsaver',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
