# Generated by Django 4.0.2 on 2022-03-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_institute', '0007_passwordsaver_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordSAver',
        ),
    ]
